### ISSUE TITLE
After declaring the winner, as a player in the game, I can know which is the “spy” song in the game and which is the normal song

### ISSUE THREAD

**Issue by YatingPan** [sopra-fs24-group-27/sopra-fs24-group-27-client#12]
### Story
After declaring the winner, as a player in the game, I can know which is the “spy” song in the game and which is the normal song.

### Acceptance criteria

- [ ] sopra-fs24-group-27/sopra-fs24-group-27-client#2

- [ ] sopra-fs24-group-27/sopra-fs24-group-27-client#4

- [ ] sopra-fs24-group-27/sopra-fs24-group-27-client#1

### Priority
Critical

### Estimate
4-6 h
