### ISSUE TITLE
After the whole game, as a player who has joined the game, I can see the score I got from the game in a new page and also the in my personal profile.

### ISSUE THREAD

**Issue by YatingPan** [sopra-fs24-group-27/sopra-fs24-group-27-client#13]
### Story
After the whole game, as a player who has joined the game, I can see the score I got from the game on a new page and also in my personal profile.

### Acceptance criteria:

- [ ] sopra-fs24-group-27/sopra-fs24-group-27-server#15

- [ ] sopra-fs24-group-27/sopra-fs24-group-27-server#16

- [ ] sopra-fs24-group-27/sopra-fs24-group-27-server#17

### Priority
Medium

### Estimate
6-8 h
